config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "flights#index"
  resources :bookings, only: [:new, :create, :show]
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, class_name: 'Flight', foreign_key: 'departure_airport_id'
  has_many :arriving_flights, class_name: 'Flight', foreign_key: 'arrival_airport_id'

  scope :departure_airports, -> { order(:code).find(Flight.pluck(:departure_airport_id)).map { |airport| [airport.code, airport.id] } }
  scope :arrival_airports, -> { order(:code).find(Flight.pluck(:arrival_airport_id)).map { |airport| [airport.code, airport.id] } }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :passengers
  belongs_to :flight

  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :departure_airport, class_name: 'Airport'
  belongs_to :arrival_airport, class_name: 'Airport'
  has_many :bookings
  has_many :passengers, through: :bookings

  scope :formatted_dates, -> { order(:start_datetime).pluck(:start_datetime).map { |date| date.strftime("%d/%m/%Y") }.uniq }

  def formatted_datetime
    start_datetime.strftime("%d/%m/%Y - %H:%M")
  end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
  has_one :flight, through: :booking

  validates :name, :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new

    if query_params_present?
      prepare_booking
    else
      redirect_to root_path
    end
  end

  def create
    @booking = Booking.new(booking_parameters)

    if @booking.save
      @booking.passengers.each { |passenger| PassengerMailer.with(passenger: passenger).registration_confirmation.deliver_now }
      redirect_to @booking
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private

  def booking_parameters
    params.require(:booking).permit(:flight_id, passengers_attributes: [:name, :email] )
  end

  def query_params_present?
    true if [:flight, :passanger_count].all? { |el| params.has_key?(el) }
  end

  def prepare_booking
    @passengers = Array.new(params[:passanger_count].to_i) { Passenger.new }
    @booking.passengers << @passengers
    @booking.flight_id = Flight.find(params[:flight]).id
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @available_flights = Flight.where(departure_airport_id: params[:departure_airport])
                                .where(arrival_airport_id:   params[:arrival_airport])
                                # this weird looking conversion must be present because LIKE isn't available for datetime types in sql
                                .where("to_char(start_datetime, 'dd/mm/yyyy') LIKE ?", params[:date])
                                # avoid N + 1 queries problem
                                .includes(:departure_airport, :arrival_airport)

    @passanger_count = params[:passanger_count]
    @departure_airports = Airport.departure_airports
    @arrival_airports = Airport.arrival_airports
    @available_dates = Flight.formatted_dates
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= asset_path 'favicon/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= asset_path 'favicon/favicon-16x16.png' %>">
<link rel="manifest" href="<%= asset_path 'favicon/site.webmanifest' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#5bbad5">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#ffffff">

app/views/bookings/_flight_table.html.erb
<div class="flight-info">
  <table>
    <thead>
      <tr>
        <th>Departure from:</th>
        <th>Arrival in:</th>
        <th>Start date time:</th>
        <th>Flight duration:</th>
      </tr>

      <tr>
        <td><%= booking.flight.departure_airport.code %></td>
        <td><%= booking.flight.arrival_airport.code %></td>
        <td><%= booking.flight.formatted_datetime %></td>
        <td><%= booking.flight.duration / 60 %> hrs <%= booking.flight.duration % 60 %> min</td>
      </tr>
    </thead>
  </table>
</div>

app/views/bookings/_passenger_template.html.erb
<%= f.fields_for :passengers_attributes, passenger, index: idx do |passenger_f| %>
    <div class="container" data-passenger-target="passenger">
        <h3>Passenger <%= idx + 1 %></h3>
        <div>
        <%= passenger_f.label :name, "Name:" %>
        <%= passenger_f.text_field :name, required: true %>
        </div>
        <div>
        <%= passenger_f.label :email, "Email:" %>
        <%= passenger_f.email_field :email, required: true %>
        </div>
        <% unless passenger_f.object.errors.empty? %>
        <div class="error-showcase">
            <ul>
            <h3>Errors:</h3>
            <% passenger_f.object.errors.full_messages.each do |message| %>
                <li><%=message%></li>
            <% end %>
            </ul>
        </div>
        <% end %>
    </div>
<% end %>

app/views/bookings/_passengers_table.html.erb
<div class="passenger-info">
  <table>
    <thead>
      <tr>
        <th></th>
        <% passengers.size.times do |i| %>
          <th>Passenger <%= i + 1 %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
    <tr>
      <th>Name</th>
      <% passengers.each do |passenger| %>
        <td><%= passenger.name %></td>
      <% end %>
    </tr>

    <tr>
      <th>Email</th>
      <% passengers.each do |passenger| %>
        <td><%= passenger.email %></td>
      <% end %>
    </tr>
    </tbody>
  </table>
</div>

app/views/bookings/new.html.erb
<%= form_with model: @booking, class: "booking-new", data: { controller: "passenger", "passenger-passenger-number-value": @booking.passengers.length } do |f| %>
  <%= render "flight_table", booking: @booking %>

  <%= f.hidden_field :flight_id, value: @booking.flight_id %>

  <div class="passengers" data-passenger-target="passengerList">
    <% @booking.passengers.each_with_index do |passenger, idx| %>
      <%= render partial: "passenger_template", locals: { passenger: passenger, idx: idx, f: f} %>
    <% end %>

    <template data-passenger-target="template" data-passenger-dynamic-passengers-value="0">
      <div class="container" data-passenger-target="passenger">
        <h3 data-passenger-target="globalLabel"></h3>
        <div>
          <%= label_tag :name, "Name:", data: { "passenger-target": "textLabel" }  %>
          <%= text_field_tag "booking[passengers_attributes][][name]", nil, required: true, data: { "passenger-target": "textField" } %>
        </div>
        <div>
          <%= label_tag :email, "Email:", data: { "passenger-target": "emailLabel" } %>
          <%= email_field_tag "booking[passengers_attributes][][name]", nil, required: true, data: { "passenger-target": "emailField" } %>
        </div>
      </div>
    </template>
  </div>

  <div class="buttons">
    <%= f.submit "Submit" %>
    <%= f.button "Add passenger", type: "button", data: { action: "passenger#add" } %>
    <%= f.button "Remove passenger", type: "button", data: { action: "passenger#remove" } %>
  </div>
<% end %>

app/views/bookings/show.html.erb
<%= render "flight_table", booking: @booking %>
<%= render "passengers_table", passengers: @booking.passengers %>

app/views/flights/_book_flight_form.html.erb
<%# available_flights isn't nil but can still be empty %>
<% if available_flights && !available_flights.empty? %>
  <%= form_with url: new_booking_path, method: :get, class: "booking" do |f| %>
    <%= f.hidden_field :passanger_count, value: @passanger_count %>
    <fieldset>
      <legend>Available flights</legend>
      <% available_flights.each do |flight| %>
        <div>
          <%= f.radio_button :flight, flight.id, required: true %>
          <%= f.label :flight, "[#{flight.formatted_datetime}, #{flight.duration} minutes] #{flight.departure_airport.code} -> #{flight.arrival_airport.code}",  value: flight.id %>
        </div>
      <% end %>
    </fieldset>

    <%= f.submit "Book a flight" %>
  <% end %>
<% end %>

app/views/flights/_search_flight_form.html.erb
<%= form_with url: root_path, method: :get, class: "search-form" do |f| %>
  <div>
    <%= f.label :departure_airport, "Departure airports:" %>
    <%= f.select :departure_airport, @departure_airports,
        { include_blank: "--Select an option--" }, { required: true } %>

    <%= f.label :arrival_airport, "Arrival airports:" %>
    <%= f.select :arrival_airport, @arrival_airports,
        { include_blank: "--Select an option--" }, { required: true } %>
  </div>

  <div>
    <%= f.label :date, "Available dates:" %>
    <%= f.select :date, @available_dates,
        { include_blank: "--Select an option--" }, { required: true }  %>

    <%= f.label :passanger_count, "Number of passangers:" %>
    <%= f.select :passanger_count, [1, 2, 3, 4],
        { include_blank: "--Select an option--" }, { required: true }  %>
  </div>

  <%= f.submit "Search" %>
<% end %>

app/views/flights/index.html.erb
<div class="flight-index">
  <%= render "search_flight_form",
             departure_airports: @departure_airports,
             arrival_airport: @arrival_airport,
             available_dates: @available_dates %>

  <%= render "book_flight_form",
             available_flights: @available_flights,
             passanger_count: @passanger_count %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flight booker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= render 'application/favicon' %>
  </head>

  <body>
    <%= link_to "[home page]", root_path, class: "homepage-nav" %>
    <%= yield %>
  </body>
</html>